<a href="https://colab.research.google.com/github/easyhardhoon/Project_Maphia/blob/master/maphia_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import tensorflow as tf

In [18]:
#과거의 데이터 준비
file = "/content/data_for_maphia.csv"
#현재까지 완성한 smart_maphia 기능까지 추가한 모델의 확률 데이터 파일을 가져옴
maphia_data = pd.read_csv(file)
maphia_data

citzien_number  maphia_number  probability
0                4              1       45.338
1                4              2       17.351
2                4              3        7.141
3                5              1       47.668
4                5              2       24.579
5                5              3        9.414
6                5              4        3.764
7                6              1       52.981
8                6              2       27.102
9                6              3       14.148
10               6              4        5.409
11               6              5        2.049
12               7              1       54.875
13               7              2       31.455
14               7              3       16.381
15               7              4        8.776
16               7              5        5.455
17               8              1       57.503
18               8              2       33.014
19               8              3       19.777
20               8              4       10.312
21               8              5        5.443
22               9              1       58.878
23               9              2       36.332
24               9              3       21.234
25               9              4       12.742
26               9              5        6.665
27              10              1       60.883
28              10              2       37.288
29              10              3       25.039
30              10              4       14.398
31              10              5        8.566

In [19]:
maphia_data.columns

Index(['citzien_number', 'maphia_number', 'probability'], dtype='object')

In [21]:
독립 = maphia_data[['citzien_number', 'maphia_number']]
종속 = maphia_data[['probability']]
print(독립.shape, 종속.shape)

(32, 2) (32, 1)


In [29]:
#모델의 구조 생성
X = tf.keras.layers.Input(shape=[2])
H = tf.keras.layers.Dense(5)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss = 'mse')


In [41]:
#데이터로 모델을 학습
model.fit(독립,종속,epochs=10000, batch_size=150, verbose = 0)
model.fit(독립,종속,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 8ms/step - loss: 1.8873
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 1.8872
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 1.8871
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 1.8869
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 1.8868
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 1.8866
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 1.8865
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 1.8864
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 1.8862
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 1.8861


In [42]:
#모델을 이용하기
model.predict(독립[:5]) 
#입력 되어있던 값 예측

array([[44.307304],
       [21.560305],
       [ 6.283556],
       [47.65362 ],
       [24.622477]], dtype=float32)

In [39]:
종속[:5]
#거의 일치하는 모습

probability
0       45.338
1       17.351
2        7.141
3       47.668
4       24.579

In [47]:
model.predict([[6,5]]) # 시민의 수 6 , 마피아의 수 5 일때 예측 . 실제 값은 2.049확률임. 

array([[3.7189069]], dtype=float32)

In [54]:
model.predict([[15,4]]) # 마피아 모델을 딥러닝 시킨 이유. csv 파일로 주어지지 않았던 값을 예측할 수 있는가
# 일련의 과정으로 확률을 구하긴 함

array([[12.53588]], dtype=float32)

In [55]:
model.predict([[20,5]])
#아직까지의 딥러닝의 한계인듯. -25 라는 말도 안되는 값이 나옴. 좀 더 정밀한 딥러닝이 필요하다

array([[-25.562649]], dtype=float32)

In [56]:
#좀 더 진화된 모델. 히든레이어를 다중으로 사용함
X = tf.keras.layers.Input(shape=[2])
H = tf.keras.layers.Dense(5)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
H = tf.keras.layers.Dense(5)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
H = tf.keras.layers.Dense(5)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
H = tf.keras.layers.Dense(5)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss = 'mse')

In [58]:
model.fit(독립,종속,epochs=10000, batch_size=150, verbose = 0)
model.fit(독립,종속,epochs=10)
#앞의 예에서는  loss 가 1.88까지만 떨어졌지만
#이 방법을 통해  loss가 0.0790 까지 떨어졌다

Epoch 1/10
1/1 [==============================] - 0s 9ms/step - loss: 0.0811
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0766
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0748
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0718
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 0.0711
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 0.0701
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0707
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 0.0717
Epoch 9/10
1/1 [==============================] - 0s 15ms/step - loss: 0.0746
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0790


In [59]:
model.predict([[20,5]])
#이렇게 하니 앞서 -25라는 말도 안되는 확률이 36.197로 훨씬 더 정밀하게 나왔다

array([[36.197655]], dtype=float32)

In [60]:
model.predict([[10,3]]) 
#실제 값 25.03. 훨씬 더 정밀해진 모습

array([[24.605293]], dtype=float32)

In [63]:
model.predict([[100,10]])
#이길 확률이 235퍼센트라는 말도 안되는 확률이 나옴. 사실 더 머신러닝이 필요함을 알 수 있었다.

array([[235.49388]], dtype=float32)